# Generated by Django 6.0.5 on 2026-05-30 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('atencion', 'Atención'), ('impulsividad', 'Impulsividad'), ('organizacion', 'Organización'), ('evaluacion', 'Evaluación'), ('transicion', 'Transición')], max_length=20)),
                ('descripcion', models.TextField()),
                ('pasos', models.JSONField(default=list)),
                ('tasa_eficacia', models.IntegerField(default=0)),
                ('sugerida_por_ia', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Estrategia',
                'verbose_name_plural': 'Estrategias',
                'db_table': 'estrategia',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('grado', models.CharField(max_length=100)),
                ('tipo_tdah', models.CharField(choices=[('Combinado', 'Combinado'), ('Inatento', 'Inatento'), ('Hiperactivo', 'Hiperactivo')], max_length=20)),
                ('fortalezas', models.JSONField(default=list)),
                ('atencion_promedio', models.IntegerField(default=0)),
                ('puntaje_participacion', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiante',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='EntradaBitacora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('Alta agitacion', 'Alta agitación'), ('Logro positivo', 'Logro positivo'), ('Ajuste de entorno', 'Ajuste de entorno')], max_length=20)),
                ('puntaje_atencion', models.IntegerField(default=0, help_text='Valor entre 0 y 100')),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, related_name='entradas_bitacora', to='api.estudiante')),
            ],
            options={
                'verbose_name': 'Entrada de Bitácora',
                'verbose_name_plural': 'Entradas de Bitácora',
                'db_table': 'entrada_bitacora',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAdaptado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=255)),
                ('tipo_material', models.CharField(max_length=100)),
                ('dificultad', models.CharField(choices=[('Basico', 'Básico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=15)),
                ('contenido_markdown', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(blank=True, db_column='estudiante_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='api.estudiante')),
            ],
            options={
                'verbose_name': 'Material Adaptado',
                'verbose_name_plural': 'Materiales Adaptados',
                'db_table': 'material_adaptado',
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='profesor',
            field=models.ForeignKey(blank=True, db_column='profesor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='api.usuario'),
        ),
    ]
