# Generated by Django 6.0.5 on 2026-06-13 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen', models.TextField()),
                ('patron', models.TextField()),
                ('sugerencia', models.TextField()),
                ('generado_en', models.DateTimeField(auto_now=True)),
                ('entradas_hash', models.CharField(max_length=64)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='api.estudiante')),
            ],
            options={
                'verbose_name': 'Análisis de Bitácora',
                'db_table': 'analisis_bitacora',
            },
        ),
    ]
